### PR TITLE
Loops

### PR DESCRIPTION
**Pull request by owenm6**
Can you both look at this guidance. It was a bit rushed but Chris has said someone needs help with this type of pattern so would be good to get it live.

### CODE REVIEW

**Comment by eliothill** [comment]
- content ✅
- images ✅
- index page ❌
- need ❓ (seems too similar to [check your answers](https://www.gov.uk/service-manual/design/check-your-answers-pages))

**Comment by owenm6** [comment]
@eliothill It is very similar to check your answers and also check and confirm. But I'm not sure you would stick a check your answers into the middle of a journey.

**Comment by eliothill** [comment]
Ok I see what you mean, I'll fix the index and we can get it out there to find out more. IMHO I think the guidance/concept may only be relevant to a multiple step loops rather than a single interaction loop if that makes sense 🙃

**Comment by owenm6** [comment]
@eliothill If we can get that into the guidance that would help

**Pull request merged**
